import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header.jsx";
import Footer from "@/components/Footer/Footer.jsx";

import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zelos - Sistema de Chamados",
  description: "Generated by create next app",
  icons: {
    icon: '/icone_definitivo.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
          <ClientLayout>
          {children}
          </ClientLayout>
       
      </body>
    </html>
  );
}
